lib/warehouse_web/router.ex
defmodule WarehouseWeb.Router do
  use WarehouseWeb, :router
  use Pow.Phoenix.Router
  use Pow.Extension.Phoenix.Router, otp_app: :warehouse

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  # BEGIN added for Pow
  pipeline :protected do
    plug Pow.Plug.RequireAuthenticated,
      error_handler: Pow.Phoenix.PlugErrorHandler
  end

  scope "/" do
    pipe_through :browser

    pow_routes()
    pow_extension_routes()
  end

  scope "/", WarehouseWeb do
    pipe_through [:browser, :protected]

    # Add your protected routes here
    resources "/checks", CheckController
    post "/checks/block/:id", CheckController, :block
  end
  # END added for Pow

  scope "/", WarehouseWeb do
    pipe_through :browser

    get "/", PageController, :index
  end
end

lib/warehouse_web/views/layout_view.ex
defmodule WarehouseWeb.LayoutView do
  use WarehouseWeb, :view
end

lib/warehouse_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Warehouse · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <header>
      <section class="container">
        <nav role="navigation">
          <ul>
            <%= if @current_user do %>
              <li>Signed in as: <%= @current_user.email %></li>
              <li><%= link "Sign out", to: Routes.pow_session_path(@conn, :delete), method: :delete %></li>
              <li><%= link "Edit account", to: Routes.pow_registration_path(@conn, :edit) %></li>
            <% else %>
              <li><%= link "Sign in", to: Routes.pow_session_path(@conn, :new) %></li>
              <li><%= link "Sign up", to: Routes.pow_registration_path(@conn, :new) %></li>
            <% end %>
            <li><%=  link "Checks", to: Routes.check_path(@conn, :index) %></li>
          </ul>
        </nav>
        <a href="http://phoenixframework.org/" class="phx-logo">
          <img src="<%= Routes.static_path(@conn, "/images/phoenix.png") %>" alt="Phoenix Framework Logo"/>
        </a>
      </section>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>